name: sqflite_support
description: sqflite support tools
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  process_run: '>=0.10.10+2'
  path:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'
dev_dependencies:
  test: ^1.6.0