name: sqflite_common_porter
description: Sqflite import and export
version: 0.2.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.9.7+1'
  csv:
  sqflite_common_ffi:

dev_dependencies:
  test:
  process_run: '>=0.10.3'
  dev_test:

