name: sqflite_server
description: Sqflite server component
version: 0.3.3
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  path:
  flutter:
    sdk: flutter
  sqflite: '>=1.3.1'
  sqflite_common_ffi: '>=0.1.0-dev.2'
  sqflite_common_server:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_common_server
    version: '>=0.3.3'
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      ref: dart2
      path: web_socket_io
    version: '>=0.2.0'
  json_rpc_2:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.7+1'


dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  process_run: '>=0.10.7'

flutter:


dependency_overrides:
  # pedantic: '>=1.9.0'
  sqflite_common_server:
    path: ../sqflite_common_server